# Projeto: Olist V2 - Analytics Engineering
# =========================================

# Identificação do projeto
name: 'olist'
version: '1.0.0'
config-version: 2

# Perfil de conexão com o snowflake
profile: 'default'

# Pacotes do projeto
# ==================
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Artefatos de build
# ==================

# Diretório dos arquivos compilados
target-path: "target"

# Diretórios removidos pelo dbt clean
clean-targets:
  - "target"
  - "dbt_packages"

# Configurações dos modelos
# =========================

models:
  olist:

    # Camada Staging
    # Limpeza, renomeação e padronização de dados
    staging:
      +schema: STAGING
      +materialized: view

    # Camada Intermediate
    # Integração e transformações intermediárias
    intermediate:
      +schema: INTERMEDIATE
      +materialized: view

    # Camada Marts / Gold
    # Modelos analíticos, fatos e dimensões
    marts:
      +schema: MARTS
      +materialized: table