USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS OLIST;

USE DATABASE OLIST;

-- Bronze / Camada Raw
CREATE SCHEMA IF NOT EXISTS RAW;

SHOW SCHEMAS IN DATABASE OLIST;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS OLIST_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- papel / função usada no dbt
CREATE ROLE IF NOT EXISTS OLIST_DBT_ROLE;

