-- Warehouse 
GRANT USAGE
ON WAREHOUSE OLIST_WH
TO ROLE OLIST_DBT_ROLE;

-- Database
GRANT USAGE
ON DATABASE OLIST
TO ROLE OLIST_DBT_ROLE;

-- Schema RAW
GRANT USAGE
ON SCHEMA OLIST.RAW
TO ROLE OLIST_DBT_ROLE;

-- Acesso à tabelas RAW existentes
GRANT SELECT
ON ALL TABLES IN SCHEMA OLIST.RAW
TO ROLE OLIST_DBT_ROLE;

-- Acesso à tabelas RAW futuras
GRANT SELECT
ON FUTURE TABLES IN SCHEMA OLIST.RAW
TO ROLE OLIST_DBT_ROLE;

-- Permissão para o dbt criar schemas
GRANT CREATE SCHEMA
ON DATABASE OLIST
TO ROLE OLIST_DBT_ROLE;

-- Verifica o usuário atual
SELECT CURRENT_USER();

-- Substitue o valor retornado por CURRENT_USER()
GRANT ROLE OLIST_DBT_ROLE
TO USER ISAIASSANTOS032;