USE ROLE ACCOUNTADMIN;
USE DATABASE OLIST;
USE SCHEMA RAW;



-- CUSTOMERS
COPY INTO CUSTOMERS
FROM @OLIST_CSV_STAGE
FILES = ('olist_customers_dataset.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'OLIST_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


-- ORDERS
COPY INTO ORDERS
FROM @OLIST_CSV_STAGE
FILES = ('olist_orders_dataset.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'OLIST_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


-- ORDER ITEMS
COPY INTO ORDER_ITEMS
FROM @OLIST_CSV_STAGE
FILES = ('olist_order_items_dataset.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'OLIST_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


-- SELLERS
COPY INTO SELLERS
FROM @OLIST_CSV_STAGE
FILES = ('olist_sellers_dataset.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'OLIST_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


-- PRODUCTS
COPY INTO PRODUCTS
FROM @OLIST_CSV_STAGE
FILES = ('olist_products_dataset.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'OLIST_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


-- GEOLOCATION
COPY INTO GEOLOCATION
FROM @OLIST_CSV_STAGE
FILES = ('olist_geolocation_dataset.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'OLIST_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


-- PRODUCT CATEGORY NAME TRANSLATION
COPY INTO PRODUCT_CATEGORY_NAME_TRANSLATION
FROM @OLIST_CSV_STAGE
FILES = ('product_category_name_translation.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'OLIST_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


-- ORDER REVIEWS
COPY INTO ORDER_REVIEWS
FROM @OLIST_CSV_STAGE
FILES = ('olist_order_reviews_dataset.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'OLIST_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


-- ORDER PAYMENTS
COPY INTO ORDER_PAYMENTS
FROM @OLIST_CSV_STAGE
FILES = ('olist_order_payments_dataset.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'OLIST_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;



-- =========
-- Validação
-- =========
SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count FROM CUSTOMERS
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM ORDERS
UNION ALL
SELECT 'ORDER_ITEMS', COUNT(*) FROM ORDER_ITEMS
UNION ALL
SELECT 'ORDER_PAYMENTS', COUNT(*) FROM ORDER_PAYMENTS
UNION ALL
SELECT 'ORDER_REVIEWS', COUNT(*) FROM ORDER_REVIEWS
UNION ALL
SELECT 'PRODUCTS', COUNT(*) FROM PRODUCTS
UNION ALL
SELECT 'SELLERS', COUNT(*) FROM SELLERS
UNION ALL
SELECT 'GEOLOCATION', COUNT(*) FROM GEOLOCATION
UNION ALL
SELECT 'PRODUCT_CATEGORY_NAME_TRANSLATION', COUNT(*)
FROM PRODUCT_CATEGORY_NAME_TRANSLATION
ORDER BY table_name;


-- Customers
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT customer_id) AS distinct_customer_ids,
    COUNT_IF(customer_id IS NULL) AS null_customer_ids
FROM CUSTOMERS;

-- Orders
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT order_id) AS distinct_order_ids,
    COUNT_IF(order_id IS NULL) AS null_order_ids
FROM ORDERS;

-- Products
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT product_id) AS distinct_product_ids,
    COUNT_IF(product_id IS NULL) AS null_product_ids
FROM PRODUCTS;

-- Sellers
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT seller_id) AS distinct_seller_ids,
    COUNT_IF(seller_id IS NULL) AS null_seller_ids
FROM SELLERS;

